CREATE TABLE roles (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nombre VARCHAR(255)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    password VARCHAR(255)
);

CREATE TABLE roles_usuarios (
    rol_id BIGINT,
    usuario_id BIGINT,
    PRIMARY KEY (usuario_id, rol_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (rol_id) REFERENCES roles(id)
);